services:
  asu_schedule_bot:
    build: .
    container_name: asu_schedule_bot
    env_file:
      - ./.env
    restart: unless-stopped
    volumes:
      - ./etc_asuschedule/logs:/asuschedule/logs
      - ./etc_asuschedule/sqlite:/asuschedule/sqlite
