[project]
name = "asu-schedule"
version = "0.0.1"
readme = "README.md"
authors = [
    { name = "bzorn", email = "v.klimenko.2137@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "environs>=15.0.1",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "python-telegram-bot[job-queue]>=21.6",
    "sqlalchemy>=2.0.35",
]

[dependency-groups]
dev = [
    "ruff>=0.15.18",
    "sort-requirements>=1.3.0",
]

[tool.ruff]
line-length = 79

[tool.ruff.format]
indent-style = "space"
quote-style = "double"

[tool.ruff.lint]
select = [
    "A",
    "ANN",
    "ARG",
    "COM",
    "E",
    "EM",
    "ERA",
    "F",
    "FIX",
    "I",
    "ISC",
    "N",
    "PTH",
    "Q",
    "RET",
    "RSE",
    "RUF",
    "T20",
    "TID",
    "UP",
    "W",
]

ignore = [
    "RUF001",
    "RUF003",
    "RUF012",
]

[tool.ruff.lint.isort]
force-sort-within-sections = true
order-by-type = false
known-first-party = [
    "consts",
    "config",
    "database",
    "enums",
    "models",
    "schedules",
    "handlers",
    "utils",
]

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true
suppress-dummy-args = true

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "double"
multiline-quotes = "double"
