name: Python application

on:
  push:
    branches: [ "master", "develop"]
  pull_request:
    branches: [ "master", "develop"]

permissions:
  contents: read

jobs:
  flake8-test:
    runs-on: ubuntu-latest
    container: python:3.13-alpine
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: pip install -r requirements/test.txt
    - name: Check code formatting with flake8
      run: flake8 ./

  prod-deploy:
    if: github.ref == 'refs/heads/master'
    needs: [ flake8-test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/ASU_Schedule
            docker compose down
            git reset --hard origin/master  
            git pull origin master
            docker compose up --build -d
            docker system prune -f